use lazy_static::lazy_static;
use prometheus::{
    register_counter_vec, register_gauge_vec, register_histogram_vec,
    CounterVec, GaugeVec, HistogramVec,
};

lazy_static! {
    static ref LOGS_INGESTED: CounterVec = register_counter_vec!(
        "siem_logs_ingested_total",
        "Total logs ingested",
        &["source", "status"]
    ).unwrap();
    
    static ref ALERTS_GENERATED: CounterVec = register_counter_vec!(
        "siem_alerts_generated_total",
        "Alerts generated by rule",
        &["rule_id", "severity"]
    ).unwrap();
    
    static ref PROCESSING_TIME: HistogramVec = register_histogram_vec!(
        "siem_log_processing_seconds",
        "Time to process a log",
        &["stage"]
    ).unwrap();
}

// In your detection engine
pub async fn process_log(&self, log: Log) {
    let start = Instant::now();
    
    // ... processing ...
    
    PROCESSING_TIME
        .with_label_values(&["total"])
        .observe(start.elapsed().as_secs_f64());
    
    ALERTS_GENERATED
        .with_label_values(&[rule.id(), &rule.severity.to_string()])
        .inc();
}